export const actionTypes = {
  SET_QUESTIONS: "SET_QUESTIONS",
  SET_LOADING_QUESTIONS: "SET_LOADING_QUESTIONS",
  SEND_QUESTION: "SEND_QUESTION",
  //SEND_ANSWER_QUESTION: "SEND_ANSWER_QUESTION"
  //DELETE_QUESTION: "DELETE_QUESTION",
  //CHANGE_QUESTION: "CHANGE_QUESTION"
};
