export const actionTypes = {
  SET_ROOMS: "SET_ROOMS",
  BOOKING_ROOM: "BOOKING_ROOM",
  CANCEL_ROOM: "CANCEL_ROOM",
  FILTER_CHANGE_ROOMS: "FILTER_CHANGE_ROOMS",
  FILTER_QUERY_SEARCH_ROOMS: "FILTER_QUERY_SEARCH_ROOMS",
  SET_LOADING_ROOMS: "SET_LOADING_ROOMS",
};
