export const actionTypes = {
  SET_ROOMS: "SET_ROOMS",
  FILTER_CHANGE_ROOMS: "FILTER_CHANGE_ROOMS",
  FILTER_QUERY_SEARCH_ROOMS: "FILTER_QUERY_SEARCH_ROOMS",
  SET_LOADING_ROOMS: "SET_LOADING_ROOMS",
  BOOKING_ROOM: "BOOKING_ROOM",
  // CANCEL_BOOKING_ROOM: "CANCEL_ROOM",
  SET_SEARCH_PARAMS_ROOMS: "SET_SEARCH_PARAMS_ROOMS",
  //ADD_ROOM: "ADD_ROOM",
  //DELETE_ROOM: "DELETE_ROOM",
  //CHANGE_ROOM: "CHANGE_ROOM"
  // SEACRH_ROOMS: "SEACRH_ROOMS",
  // RESET_SEARCHFIELD_ROOMS: "RESET_SEARCHFIELD_ROOMS",
};
