export const actionTypes = {
  SET_ROOMS: "SET_ROOMS",
  FILTER_CHANGE_ROOMS: "FILTER_CHANGE_ROOMS",
  FILTER_QUERY_SEARCH_ROOMS: "FILTER_QUERY_SEARCH_ROOMS",
  SET_LOADING_ROOMS: "SET_LOADING_ROOMS",
  BOOKING_ROOM: "BOOKING_ROOM",
  CANCEL_BOOKING_ROOM: "CANCEL_BOOKING_ROOM",
  SET_SEARCH_PARAMS_ROOMS: "SET_SEARCH_PARAMS_ROOMS",
  CHANGE_RATING: "CHANGE_RATING",
};
