export const actionTypes = {
  SET_LOADING_USER: "SET_LOADING_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_OUT: "LOGIN_OUT",
  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  REGISTRATION_FAILURE: "REGISTRATION_FAILURE",
  RESET_ERROR_FIELDS: "RESET_ERROR_FIELDS",
  UPDATE_AFTER_BOOKING: "UPDATE_AFTER_BOOKING",
  UPDATE_INFO_PROFILE: "UPDATE_INFO_PROFILE",
  CANCEL_BOOKING: "CANCEL_BOOKING",
  CHANGE_PHOTO: "CHANGE_PHOTO",
};
