export const actionTypes = {
  SET_LOADING_USER: "SET_LOADING_ROOMS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_OUT: "LOGIN_OUT",
  UPDATE_DATA_PROFILE: "UPDATE_DATA_PROFILE",
};
