export const actionTypes = {
  SET_NEWS: "SET_NEWS",
  FILTER_QUERY_SEARCH_NEWS: "FILTER_QUERY_SEARCH_NEWS",
  SET_LOADING_NEWS: "SET_LOADING_NEWS",
  //ADD_NEWS: "ADD_NEWS",
  //DELETE_NEWS: "DELETE_NEWS",
  //CHANGE_NEWS: "CHANGE_NEWS"
};
